import 'package:myshopping/models/product.dart';

class MyProducts{
  static List<Products> allProducts=[
    Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/Shoe.png", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe2.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe3.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe4.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
  ];
      static List<Products>sneakersList =[
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/Shoe.png", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe2.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe3.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe4.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),

      ];


      static List<Products> jackets =[
         Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/Shoe.png", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe2.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe3.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),
        Products(id: 1,
     name: "Nike Air Max ",
      category: "Trending Now" ,
       image: "assets/images/shoe4.jpg", 
       description: "clean,",
        price: 1800, 
        quantity: 1),


      ];

}